<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Rs. 2400</name>
   <tag></tag>
   <elementGuidId>2d345d4c-689e-45d4-a2c1-c2a75959bf5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.cart_total_price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='product-2']/td[5]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3c3ba319-11b5-4d15-a200-4901b0121654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart_total_price</value>
      <webElementGuid>7ffe10a6-26af-4402-a3be-2041f5904653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rs. 2400</value>
      <webElementGuid>76c19228-5c16-49f0-b19f-e9e75fa2be73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-2&quot;)/td[@class=&quot;cart_total&quot;]/p[@class=&quot;cart_total_price&quot;]</value>
      <webElementGuid>ad3e3d97-d06d-4999-9d6d-6a88de057a7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='product-2']/td[5]/p</value>
      <webElementGuid>971bbebc-c5e2-4a1f-b137-d1d532f0d8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men Tshirt'])[1]/following::p[3]</value>
      <webElementGuid>cdfa3448-d81f-4e47-a407-8f2e7478818a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::p[3]</value>
      <webElementGuid>a4d77eee-1d66-40a3-9bc4-b72c10c3fcba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart is empty!'])[1]/preceding::p[1]</value>
      <webElementGuid>8ae26457-07cb-4a7a-a001-1d5e749dd31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[1]/preceding::p[1]</value>
      <webElementGuid>cea9d997-c252-49f7-80b4-d7f93641ab02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rs. 2400']/parent::*</value>
      <webElementGuid>29b030aa-c258-4ab6-a92c-3a5706e198a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/p</value>
      <webElementGuid>02c326c5-0e98-4893-b06c-8fd630bfb1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Rs. 2400' or . = 'Rs. 2400')]</value>
      <webElementGuid>eb8fc5f2-64d1-40f7-b925-91917bd79544</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
